---
title: "Programa"
authot: 
  - name: Estación R + Elian Soutullo
site: distill::distill_website
---


### Módulo I: Introducción
  
- ¿Qué es Shiny? ¿Por qué Shiny? Alcances y ejemplos de aplicaciones desarrolladas con Shiny.

- Funcionamiento y arquitectura básica de una app. UI + Server.

- Cómo crear un proyecto de app. 

  

### Módulo II: UI (frontend)

- ¿Por dónde empiezo? Prototipo y diseño de la UI. Componentes base (framework): page, layout, panels, navbar, tabset, rows,columns, etc.

- Tipos de inputs.

### Módulo III: Server (backend)

- Cargando mis propios datos a una app. Conexión con la UI. 

- Programación reactiva. Reactives y Observers. 


### Módulo IV: Mi primera Shiny
  
- Desarrollo de una app de principio a fin. Inputs + Outputs + Renders + Reactivos

### Módulo IV: Compartiendo mi app
  
- Compartir la app (deploy) a través de diferentes opciones. Publicacion de la app en shinyapps.io (gratis).

- ¿Cómo seguir? 

- Recursos adicionales: books, frameworks, paquetes y buenas prácticas.